# Generated by Django 3.1.6 on 2021-02-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='add_notes',
            field=models.TextField(default=''),
        ),
    ]
