# Generated by Django 3.1.6 on 2021-03-02 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0007_delete_participant'),
        ('clients', '0005_auto_20210220_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_number', models.CharField(editable=False, max_length=32)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('date_of_birth', models.DateField()),
                ('address_line', models.CharField(max_length=254)),
                ('postcode', models.CharField(max_length=10)),
                ('emergency_contact_name', models.CharField(max_length=64)),
                ('emergency_contact_number', models.CharField(max_length=20)),
                ('dec_illness', models.CharField(blank=True, max_length=254, null=True)),
                ('dec_medication', models.CharField(blank=True, max_length=254, null=True)),
                ('dec_abs_cond', models.BooleanField(default=False)),
                ('acknowledgement_of_risk', models.BooleanField(default=False)),
                ('signed_by', models.CharField(max_length=64)),
                ('date_signed', models.DateField()),
                ('risk_form', models.FileField(blank=True, null=True, upload_to='')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client')),
            ],
        ),
    ]
