# Generated by Django 3.1.6 on 2021-03-03 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riskforms', '0002_auto_20210302_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='acknowledgement_of_risk',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='date_signed',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='dec_abs_cond',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='dec_illness',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='dec_medication',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='form_number',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='risk_form',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='signed_by',
        ),
        migrations.CreateModel(
            name='RAForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_number', models.CharField(editable=False, max_length=32)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('date_of_birth', models.DateField()),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address_line', models.CharField(max_length=254)),
                ('postcode', models.CharField(max_length=10)),
                ('emergency_contact_name', models.CharField(max_length=64)),
                ('emergency_contact_number', models.CharField(max_length=20)),
                ('dec_illness', models.CharField(blank=True, max_length=254, null=True)),
                ('dec_medication', models.CharField(blank=True, max_length=254, null=True)),
                ('dec_abs_cond', models.BooleanField(default=False)),
                ('acknowledgement_of_risk', models.BooleanField(default=False)),
                ('signed_by', models.CharField(max_length=64)),
                ('date_signed', models.DateField()),
                ('risk_form', models.FileField(blank=True, null=True, upload_to='')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riskforms.participant')),
            ],
        ),
    ]
