# Generated by Django 3.1.6 on 2021-03-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskforms', '0003_auto_20210303_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='address_line',
            new_name='address_line1',
        ),
        migrations.RenameField(
            model_name='raform',
            old_name='address_line',
            new_name='address_line1',
        ),
        migrations.AddField(
            model_name='participant',
            name='address_line2',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='address_line3',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='raform',
            name='address_line2',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='raform',
            name='address_line3',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
