# Generated by Django 3.1.6 on 2021-03-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskforms', '0004_auto_20210305_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='town_or_city',
            field=models.CharField(default=' ', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone_number',
            field=models.CharField(default=123456789, max_length=15),
            preserve_default=False,
        ),
    ]
