# Generated by Django 3.1.6 on 2021-03-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_auto_20210303_1518'),
        ('riskforms', '0006_auto_20210309_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='appointment',
        ),
        migrations.AddField(
            model_name='participant',
            name='appointment',
            field=models.ManyToManyField(to='appointments.Appointment'),
        ),
    ]
