# Generated by Django 3.1.6 on 2021-03-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskforms', '0007_auto_20210310_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raform',
            name='dec_illness',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raform',
            name='dec_medication',
            field=models.TextField(blank=True, null=True),
        ),
    ]
