# Generated by Django 3.1.6 on 2021-03-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskforms', '0009_auto_20210316_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raform',
            name='risk_form',
            field=models.FileField(upload_to='media/'),
        ),
    ]
