# Generated by Django 3.1.6 on 2021-03-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskforms', '0011_auto_20210316_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raform',
            name='risk_form',
            field=models.FileField(blank=True, null=True, upload_to='raforms/'),
        ),
    ]
