# Generated by Django 3.1.6 on 2021-03-17 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riskforms', '0012_auto_20210316_1534'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RAForm',
        ),
    ]
