# Generated by Django 3.1.6 on 2021-03-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskforms', '0013_delete_raform'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='manual_form',
            field=models.FileField(blank=True, null=True, upload_to='raforms/'),
        ),
    ]
