# Generated by Django 3.1.6 on 2021-03-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskforms', '0016_participant_manual_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='manual_form',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
