# Generated by Django 3.1.6 on 2021-03-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskforms', '0017_auto_20210318_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='manual_form',
        ),
        migrations.AddField(
            model_name='participant',
            name='media_acceptance',
            field=models.BooleanField(default=True),
        ),
    ]
