# Generated by Django 3.1.6 on 2021-03-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskforms', '0018_auto_20210323_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='manual_form',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
