# Generated by Django 3.1.6 on 2021-03-28 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riskforms', '0019_participant_manual_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='manual_form',
        ),
    ]
