# Generated by Django 3.1.6 on 2021-02-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('street_address1', models.CharField(blank=True, max_length=254, null=True)),
                ('street_address2', models.CharField(blank=True, max_length=254, null=True)),
                ('postcode', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
