# Generated by Django 3.1.6 on 2021-02-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20210210_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='root_of_inquiry',
            field=models.CharField(default='Other', max_length=254),
        ),
    ]
