# Generated by Django 3.1.6 on 2021-02-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_town_or_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='root_of_inquiry',
            field=models.CharField(choices=[('REF', 'Referral'), ('OTH', 'Other')], default='OTH', max_length=3),
        ),
    ]
