# Generated by Django 3.1.6 on 2021-03-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20210220_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='root_of_inquiry',
            field=models.CharField(choices=[('REF', 'Referral'), ('EML', 'Email'), ('WEB', 'Website'), ('PHO', 'Phone'), ('FAB', 'Facebook'), ('F2F', 'Face To Face'), ('INS', 'Instagram'), ('TWT', 'Twitter'), ('OTH', 'Other')], default='OTH', max_length=3),
        ),
    ]
