# Generated by Django 3.1.6 on 2021-03-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20210303_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='abbreviation',
            field=models.CharField(default='DEF', max_length=3),
        ),
    ]
