# Generated by Django 3.1.6 on 2021-03-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_client_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='abbreviation',
            field=models.CharField(max_length=3),
        ),
    ]
