# Generated by Django 3.1.6 on 2021-02-25 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_ispaid'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Checkout',
            new_name='Payment',
        ),
        migrations.CreateModel(
            name='RiskAcknowledgement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledgement_no', models.CharField(max_length=32)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('appointment_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riskacknowledgement', to='appointments.appointment')),
            ],
        ),
    ]
