# Generated by Django 3.1.6 on 2021-02-27 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_issolo'),
        ('checkout', '0003_auto_20210225_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='appointment_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.appointment'),
        ),
    ]
