# Generated by Django 3.1.6 on 2021-02-27 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20210227_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='appointment_no',
            new_name='appointment',
        ),
    ]
