# Generated by Django 3.1.6 on 2021-03-23 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20210227_1256'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RiskAcknowledgement',
        ),
    ]
