# Generated by Django 3.1.6 on 2021-04-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0013_auto_20210331_1041'),
        ('checkout', '0007_auto_20210324_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='appointment',
        ),
        migrations.AddField(
            model_name='payment',
            name='appointment',
            field=models.ManyToManyField(to='appointments.Appointment'),
        ),
    ]
