# Generated by Django 3.1.6 on 2021-03-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('reference', models.CharField(max_length=32)),
                ('classification', models.CharField(choices=[('PAR', 'Participant'), ('PAY', 'Payment')], max_length=3)),
            ],
        ),
    ]
