# Generated by Django 3.1.6 on 2021-03-24 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_auto_20210303_1518'),
        ('checkout', '0006_delete_riskacknowledgement'),
        ('riskforms', '0018_auto_20210323_0645'),
        ('home', '0003_notification_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='notification',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='riskforms.participant'),
        ),
        migrations.AddField(
            model_name='notification',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkout.payment'),
        ),
    ]
