# Generated by Django 3.1.6 on 2021-02-22 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0005_auto_20210220_1502'),
        ('activities', '0002_course_add_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_number', models.CharField(max_length=11)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('appointment_participants', models.SmallIntegerField(default=1)),
                ('appointment_location', models.CharField(blank=True, max_length=254, null=True)),
                ('appointment_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.activity')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.course')),
            ],
        ),
    ]
