# Generated by Django 3.1.6 on 2021-02-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
    ]
