# Generated by Django 3.1.6 on 2021-02-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_ispaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='isSolo',
            field=models.BooleanField(default=True),
        ),
    ]
