# Generated by Django 3.1.6 on 2021-03-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='form_number',
            field=models.CharField(default='Poop', editable=False, max_length=32),
            preserve_default=False,
        ),
    ]
