# Generated by Django 3.1.6 on 2021-03-02 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_participant_form_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='declaration_absence_cond',
            new_name='dec_abs_cond',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='declaration_illness',
            new_name='dec_illness',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='declaration_medication',
            new_name='dec_medication',
        ),
    ]
