# Generated by Django 3.1.6 on 2021-03-02 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_auto_20210302_0743'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
