# Generated by Django 3.1.6 on 2021-03-03 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_appointment_add_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='add_note',
            new_name='add_notes',
        ),
    ]
