# Generated by Django 3.1.6 on 2021-03-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_auto_20210303_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='paymentRequest',
            field=models.SmallIntegerField(default=0),
        ),
    ]
