# Generated by Django 3.1.6 on 2021-03-30 10:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_appointment_paymentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='paymentSent',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
