# Generated by Django 3.1.6 on 2021-03-31 10:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_auto_20210330_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='paymentSent',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
